CURRENCY_CHOICES = [
        ('USD', 'US Dollar'),
        ('IRR', 'Iranian Rial'),
        ('EUR', 'Euro'),
        ('GBP', 'British Pound'),
        ('JPY', 'Japanese Yen'),
        ('CHF', 'Swiss Franc'),
        ('CAD', 'Canadian Dollar'),
        ('AUD', 'Australian Dollar'),    
        ('NZD', 'New Zealand Dollar'),
        ('CNY', 'Chinese Yuan'),
        ('INR', 'Indian Rupee'),
        ('RUB', 'Russian Ruble'),
        ('BRL', 'Brazilian Real'),
        ('ZAR', 'South African Rand'),
        ('KRW', 'South Korean Won'),
        ('MXN', 'Mexican Peso'),
        ('SGD', 'Singapore Dollar'),
        ('HKD', 'Hong Kong Dollar'),
        ('SEK', 'Swedish Krona'),
        ('NOK', 'Norwegian Krone'),
        ('TRY', 'Turkish Lira'),
    ]


CATEGORIES_CHOICES = [
    ("software", "Software"),
    ("mobile_apps", "Mobile Apps"),
    ("games", "Games"),
    ("ebooks", "eBooks"),
    ("audiobooks", "Audiobooks"),
    ("articles", "Articles & Research Papers"),
    ("music", "Music & Audio"),
    ("sound_effects", "Sound Effects"),
    ("videos", "Videos & Stock Footage"),
    ("courses", "Online Courses"),
    ("web_templates", "Web Templates"),
    ("wordpress_themes", "WordPress Themes"),
    ("plugins", "Plugins & Extensions"),
    ("graphic_designs", "Graphic Designs"),
    ("illustrations", "Illustrations & Vectors"),
    ("fonts", "Fonts"),
    ("3d_models", "3D Models"),
    ("photos", "Stock Photos"),
    ("code_snippets", "Code Snippets"),
    ("scripts", "Scripts & Automation"),
    ("presentation_templates", "Presentation Templates"),
    ("resumes", "Resume & CV Templates"),
    ("ui_kits", "UI Kits"),
    ("mockups", "Mockups"),
    ("branding_kits", "Branding Kits"),
    ("marketing_materials", "Marketing Materials"),
    ("email_templates", "Email Templates"),
    ("datasets", "Datasets"),
    ("notion_templates", "Notion Templates"),
    ("figma_templates", "Figma Templates"),
    ("canva_templates", "Canva Templates"),
    ("subscription_services", "Subscription Services"),
    ("licenses", "License Keys & Activations"),
    ("tools", "Digital Tools & Utilities"),
    ("cloud_files", "Cloud Storage Files"),
    ("ai_assets", "AI Assets & Prompts"),
    ("nft_digital_art", "NFTs & Digital Art"),
    ("wallpapers", "Wallpapers"),
    ("printables", "Printables"),
    ("custom_requests", "Custom Digital Orders"),
    ("other", "Other"),
]
