# Generated by Django 5.2.2 on 2025-06-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='currency_type',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('IRR', 'Iranian Rial'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CHF', 'Swiss Franc'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('RUB', 'Russian Ruble'), ('BRL', 'Brazilian Real'), ('ZAR', 'South African Rand'), ('KRW', 'South Korean Won'), ('MXN', 'Mexican Peso'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('TRY', 'Turkish Lira')], max_length=20),
        ),
    ]
