# Generated by Django 5.2.2 on 2025-06-14 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_products_currency_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
