let CATEGORIES = [
    ["all", "All"],
    ["electronics", "Electronics"],
    ["computers_accessories", "Computers & Accessories"],
    ["mobile_phones_accessories", "Mobile Phones & Accessories"],
    ["home_appliances", "Home Appliances"],
    ["furniture", "Furniture"],
    ["clothing", "Clothing"],
    ["mens_clothing", "Men's Clothing"],
    ["womens_clothing", "Women's Clothing"],
    ["kids_clothing", "Kids' Clothing"],
    ["shoes", "Shoes"],
    ["sports_outdoors", "Sports & Outdoors"],
    ["fitness_equipment", "Fitness Equipment"],
    ["health_personal_care", "Health & Personal Care"],
    ["beauty_cosmetics", "Beauty & Cosmetics"],
    ["toys_games", "Toys & Games"],
    ["books", "Books"],
    ["music_instruments", "Music & Instruments"],
    ["automotive", "Automotive"],
    ["tools_home_improvement", "Tools & Home Improvement"],
    ["garden_outdoor", "Garden & Outdoor"],
    ["pet_supplies", "Pet Supplies"],
    ["groceries_gourmet_food", "Groceries & Gourmet Food"],
    ["office_supplies", "Office Supplies"],
    ["baby_products", "Baby Products"],
    ["jewelry_watches", "Jewelry & Watches"],
    ["arts_crafts", "Arts & Crafts"],
    ["industrial_scientific", "Industrial & Scientific"],
    ["software", "Software"],
    ["video_games", "Video Games"],
    ["movies_tv_shows", "Movies & TV Shows"],
    ["travel_luggage", "Travel & Luggage"],
    ["musical_instruments", "Musical Instruments"],
    ["collectibles_memorabilia", "Collectibles & Memorabilia"],
    ["stationery", "Stationery"],
    ["smart_home_devices", "Smart Home Devices"],
    ["food_beverages", "Food & Beverages"],
    ["safety_security", "Safety & Security"],
    ["party_supplies", "Party Supplies"],
    ["accessories", "Accessories"],
    ["handmade_products", "Handmade Products"],
    ["digital_products", "Digital Products"],
    ["subscription_services", "Subscription Services"],
    ["other", "Other"],
]
export default CATEGORIES;