# Generated by Django 5.2.1 on 2025-07-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_banners_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
