# Generated by Django 5.2.1 on 2025-07-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_banners_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
