# Generated by Django 5.2.1 on 2025-07-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0004_banners_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='banners',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
