# Generated by Django 5.2.2 on 2025-06-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
