# Generated by Django 5.2.2 on 2025-06-16 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd_api', '0003_productstars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discription',
            field=models.TextField(max_length=3000),
        ),
    ]
