# Generated by Django 5.2.2 on 2025-07-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd_api', '0010_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='condition',
            field=models.CharField(default='New', max_length=25),
        ),
    ]
