# Generated by Django 5.2.1 on 2025-07-17 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd_api', '0013_alter_products_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='likes',
        ),
        migrations.DeleteModel(
            name='ProductLikes',
        ),
    ]
