# Generated by Django 5.2.1 on 2025-07-19 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd_api', '0014_remove_products_likes_delete_productlikes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=3000)),
                ('price', models.IntegerField()),
                ('currency_type', models.CharField(choices=[('USD', 'US Dollar'), ('IRR', 'Iranian Rial'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('JPY', 'Japanese Yen'), ('CHF', 'Swiss Franc'), ('CAD', 'Canadian Dollar'), ('AUD', 'Australian Dollar'), ('NZD', 'New Zealand Dollar'), ('CNY', 'Chinese Yuan'), ('INR', 'Indian Rupee'), ('RUB', 'Russian Ruble'), ('BRL', 'Brazilian Real'), ('ZAR', 'South African Rand'), ('KRW', 'South Korean Won'), ('MXN', 'Mexican Peso'), ('SGD', 'Singapore Dollar'), ('HKD', 'Hong Kong Dollar'), ('SEK', 'Swedish Krona'), ('NOK', 'Norwegian Krone'), ('TRY', 'Turkish Lira')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='files/images/')),
                ('stars', models.IntegerField(default=0, null=True)),
                ('condition', models.CharField(default='New', max_length=25)),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('computers_accessories', 'Computers & Accessories'), ('mobile_phones_accessories', 'Mobile Phones & Accessories'), ('home_appliances', 'Home Appliances'), ('furniture', 'Furniture'), ('clothing', 'Clothing'), ('mens_clothing', "Men's Clothing"), ('womens_clothing', "Women's Clothing"), ('kids_clothing', "Kids' Clothing"), ('shoes', 'Shoes'), ('sports_outdoors', 'Sports & Outdoors'), ('fitness_equipment', 'Fitness Equipment'), ('health_personal_care', 'Health & Personal Care'), ('beauty_cosmetics', 'Beauty & Cosmetics'), ('toys_games', 'Toys & Games'), ('books', 'Books'), ('music_instruments', 'Music & Instruments'), ('automotive', 'Automotive'), ('tools_home_improvement', 'Tools & Home Improvement'), ('garden_outdoor', 'Garden & Outdoor'), ('pet_supplies', 'Pet Supplies'), ('groceries_gourmet_food', 'Groceries & Gourmet Food'), ('office_supplies', 'Office Supplies'), ('baby_products', 'Baby Products'), ('jewelry_watches', 'Jewelry & Watches'), ('arts_crafts', 'Arts & Crafts'), ('industrial_scientific', 'Industrial & Scientific'), ('software', 'Software'), ('video_games', 'Video Games'), ('movies_tv_shows', 'Movies & TV Shows'), ('travel_luggage', 'Travel & Luggage'), ('musical_instruments', 'Musical Instruments'), ('collectibles_memorabilia', 'Collectibles & Memorabilia'), ('stationery', 'Stationery'), ('smart_home_devices', 'Smart Home Devices'), ('food_beverages', 'Food & Beverages'), ('safety_security', 'Safety & Security'), ('party_supplies', 'Party Supplies'), ('accessories', 'Accessories'), ('handmade_products', 'Handmade Products'), ('digital_products', 'Digital Products'), ('subscription_services', 'Subscription Services'), ('other', 'Other')], default='others', max_length=25)),
                ('digital_file', models.FileField(upload_to='files/digital/')),
                ('file_format', models.CharField(blank=True, max_length=10, null=True)),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('license_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd_api.product'),
        ),
        migrations.AlterField(
            model_name='productincart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd_api.product'),
        ),
        migrations.AlterField(
            model_name='productstars',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prd_api.product'),
        ),
        migrations.DeleteModel(
            name='products',
        ),
    ]
