# Generated by Django 5.2.1 on 2025-07-19 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prd_api', '0015_product_alter_productcomment_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='condition',
        ),
    ]
