# Generated by Django 5.2.1 on 2025-07-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prd_api', '0016_remove_product_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('mobile_apps', 'Mobile Apps'), ('games', 'Games'), ('ebooks', 'eBooks'), ('audiobooks', 'Audiobooks'), ('articles', 'Articles & Research Papers'), ('music', 'Music & Audio'), ('sound_effects', 'Sound Effects'), ('videos', 'Videos & Stock Footage'), ('courses', 'Online Courses'), ('web_templates', 'Web Templates'), ('wordpress_themes', 'WordPress Themes'), ('plugins', 'Plugins & Extensions'), ('graphic_designs', 'Graphic Designs'), ('illustrations', 'Illustrations & Vectors'), ('fonts', 'Fonts'), ('3d_models', '3D Models'), ('photos', 'Stock Photos'), ('code_snippets', 'Code Snippets'), ('scripts', 'Scripts & Automation'), ('presentation_templates', 'Presentation Templates'), ('resumes', 'Resume & CV Templates'), ('ui_kits', 'UI Kits'), ('mockups', 'Mockups'), ('branding_kits', 'Branding Kits'), ('marketing_materials', 'Marketing Materials'), ('email_templates', 'Email Templates'), ('datasets', 'Datasets'), ('notion_templates', 'Notion Templates'), ('figma_templates', 'Figma Templates'), ('canva_templates', 'Canva Templates'), ('subscription_services', 'Subscription Services'), ('licenses', 'License Keys & Activations'), ('tools', 'Digital Tools & Utilities'), ('cloud_files', 'Cloud Storage Files'), ('ai_assets', 'AI Assets & Prompts'), ('nft_digital_art', 'NFTs & Digital Art'), ('wallpapers', 'Wallpapers'), ('printables', 'Printables'), ('custom_requests', 'Custom Digital Orders'), ('other', 'Other')], default='others', max_length=25),
        ),
    ]
